name: Auto-merge PRs
on:
  pull_request:
    types: [opened, labeled, synchronize, reopened]
  check_suite:
    types: [completed]
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    if: >
      github.event_name != 'pull_request' ||
      contains(github.event.pull_request.labels.*.name, 'automerge')
    
    steps:
      - name: Wait for CI to complete
        if: github.event_name == 'pull_request'
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: 'CI / all_checks_passed'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
          
      - name: Enable auto-merge
        if: github.event_name == 'pull_request'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
          
      - name: Auto-merge completed PR
        if: github.event_name != 'pull_request'
        uses: pascalgn/merge-action@v0.15.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
          merge_commit_message: automatic
          merge_forks: false
          merge_labels: automerge
          merge_remove_labels: automerge
          merge_delete_branch: true